/**
 * 咒印小英雄 - Game Configuration Data
 * Roguelike Survivor H5 Game
 */

const GameData = {
  GAME_CONFIG: {
    GAME_DURATION: 480,
    MAX_ENEMIES: 35,
    MAX_ACTIVE_SKILLS: 4,
    MAX_PASSIVE_SKILLS: 3,
    PLAYER_BASE_SPEED: 150,
    PLAYER_BASE_PICKUP_RANGE: 50,
    GOLD_PER_GAME_BASE: 250,
    BOSS_TIMES: [120, 240, 480],
    expPerLevel: function (level) {
      return level * 10 + 20;
    },
  },

  ROLES: {
    swordsman: {
      id: 'swordsman',
      name: '剑客',
      description: '近战剑士，擅长飞剑攻击',
      skill: 'flying_sword',
      unlockCondition: null,
      upgradeCost: [0, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
      hpGrowth:      [5, 6, 7, 8, 9, 10, 11, 12, 14, 16],
      attackGrowth:  [100, 112, 125, 140, 156, 174, 194, 216, 240, 268],
      skillLevels:   [1, 2, 3, 4, 5, 5, 5, 5, 5, 5],
      color: '#4488FF',
    },
    mage: {
      id: 'mage',
      name: '法师',
      description: '远程法师，擅长火球术',
      skill: 'fireball',
      unlockCondition: { role: 'swordsman', level: 3 },
      upgradeCost: [0, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
      hpGrowth:      [4, 5, 6, 7, 8, 9, 10, 11, 12, 14],
      attackGrowth:  [95, 107, 120, 135, 152, 170, 190, 213, 238, 266],
      skillLevels:   [1, 2, 3, 4, 5, 5, 5, 5, 5, 5],
      color: '#FF4444',
    },
    summoner: {
      id: 'summoner',
      name: '召唤师',
      description: '召唤亡灵为己战斗',
      skill: 'summon',
      unlockCondition: { role: 'mage', level: 3 },
      upgradeCost: [0, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
      hpGrowth:      [5, 6, 7, 8, 9, 10, 11, 12, 14, 16],
      attackGrowth:  [90, 101, 114, 128, 144, 162, 182, 204, 229, 256],
      skillLevels:   [1, 2, 3, 4, 5, 5, 5, 5, 5, 5],
      color: '#AA44FF',
    },
    icemaiden: {
      id: 'icemaiden',
      name: '冰女',
      description: '冰系法师，擅长冰环冻结',
      skill: 'ice_ring',
      unlockCondition: { role: 'summoner', level: 3 },
      upgradeCost: [0, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
      hpGrowth:      [4, 5, 6, 7, 8, 9, 10, 11, 12, 14],
      attackGrowth:  [98, 110, 124, 139, 156, 175, 196, 220, 246, 276],
      skillLevels:   [1, 2, 3, 4, 5, 5, 5, 5, 5, 5],
      color: '#44DDFF',
    },
  },

  SKILLS: {
    flying_sword: {
      id: 'flying_sword',
      name: '飞剑',
      description: '发射一把穿透性飞剑，直线贯穿敌人',
      evolveDescription: '进化：散射3把飞剑呈扇形展开',
      baseDamage: 30,
      baseCooldown: 1.2,
      baseRange: 300,
      color: '#66BBFF',
    },
    fireball: {
      id: 'fireball',
      name: '火球',
      description: '发射追踪火球，命中后产生小范围爆炸',
      evolveDescription: '进化：爆炸半径+50%，附加灼烧效果',
      baseDamage: 40,
      baseCooldown: 1.8,
      baseRange: 250,
      color: '#FF6622',
    },
    ice_ring: {
      id: 'ice_ring',
      name: '冰环',
      description: '以自身为中心释放冰环，冻结周围敌人',
      evolveDescription: '进化：冻结结束后产生碎裂伤害',
      baseDamage: 25,
      baseCooldown: 2.5,
      baseRange: 120,
      color: '#88EEFF',
    },
    lightning: {
      id: 'lightning',
      name: '雷电',
      description: '随机落雷打击屏幕内敌人',
      evolveDescription: '进化：闪电链，弹射3次',
      baseDamage: 50,
      baseCooldown: 2.0,
      baseRange: 400,
      color: '#FFEE44',
    },
    whirlwind: {
      id: 'whirlwind',
      name: '旋风',
      description: '环绕玩家旋转的旋风，持续造成伤害',
      evolveDescription: '进化：同时存在2个旋风',
      baseDamage: 15,
      baseCooldown: 0.5,
      baseRange: 80,
      color: '#88FF88',
    },
    summon: {
      id: 'summon',
      name: '召唤',
      description: '召唤骷髅战士为你战斗',
      evolveDescription: '进化：同时召唤2只骷髅',
      baseDamage: 20,
      baseCooldown: 5.0,
      baseRange: 200,
      color: '#CC88FF',
    },
  },

  PASSIVE_SKILLS: {
    damage_boost: {
      id: 'damage_boost',
      name: '咒力强化',
      description: '提升伤害',
      bonusPerLevel: 0.10,
      maxLevel: 5,
      icon: '💥',
    },
    attack_speed: {
      id: 'attack_speed',
      name: '攻速强化',
      description: '提升攻击速度',
      bonusPerLevel: 0.08,
      maxLevel: 5,
      icon: '⚡',
    },
    range_boost: {
      id: 'range_boost',
      name: '范围扩大',
      description: '扩大技能范围',
      bonusPerLevel: 0.10,
      maxLevel: 5,
      icon: '🔵',
    },
    move_speed: {
      id: 'move_speed',
      name: '移速提升',
      description: '提升移动速度',
      bonusPerLevel: 0.08,
      maxLevel: 5,
      icon: '👟',
    },
    pickup_range: {
      id: 'pickup_range',
      name: '拾取范围',
      description: '扩大经验拾取范围',
      bonusPerLevel: 0.15,
      maxLevel: 3,
      icon: '🧲',
    },
    max_hp: {
      id: 'max_hp',
      name: '生命上限',
      description: '提升最大生命值',
      bonusPerLevel: 0.15,
      maxLevel: 3,
      icon: '❤️',
    },
  },

  TALENTS: {
    attack: {
      name: '攻击',
      talents: {
        attack_power: {
          id: 'attack_power',
          name: '咒力强化',
          description: '提升攻击力',
          levels: [
            { bonus: 0.05, cost: 100 },
            { bonus: 0.10, cost: 200 },
            { bonus: 0.15, cost: 300 },
          ],
        },
        critical_rate: {
          id: 'critical_rate',
          name: '致命一击',
          description: '提升暴击率',
          levels: [
            { bonus: 0.03, cost: 100 },
            { bonus: 0.06, cost: 200 },
            { bonus: 0.10, cost: 300 },
          ],
        },
        critical_damage: {
          id: 'critical_damage',
          name: '弱点洞察',
          description: '提升暴击伤害',
          levels: [
            { bonus: 0.20, cost: 100 },
            { bonus: 0.40, cost: 200 },
            { bonus: 0.60, cost: 300 },
          ],
        },
      },
    },
    defense: {
      name: '防御',
      talents: {
        toughness: {
          id: 'toughness',
          name: '坚韧',
          description: '提升最大生命值',
          levels: [
            { bonus: 1, cost: 100 },
            { bonus: 2, cost: 200 },
            { bonus: 3, cost: 300 },
          ],
        },
        regen: {
          id: 'regen',
          name: '再生',
          description: '每30秒恢复生命',
          levels: [
            { bonus: 1, cost: 100 },
            { bonus: 2, cost: 200 },
            { bonus: 3, cost: 300 },
          ],
        },
        invincible: {
          id: 'invincible',
          name: '不屈',
          description: '受击后无敌时间延长',
          levels: [
            { bonus: 0.3, cost: 100 },
            { bonus: 0.6, cost: 200 },
            { bonus: 1.0, cost: 300 },
          ],
        },
      },
    },
    growth: {
      name: '成长',
      talents: {
        wisdom: {
          id: 'wisdom',
          name: '悟性',
          description: '提升经验获取',
          levels: [
            { bonus: 0.10, cost: 100 },
            { bonus: 0.20, cost: 200 },
            { bonus: 0.30, cost: 300 },
          ],
        },
        magnet: {
          id: 'magnet',
          name: '吸灵',
          description: '提升拾取范围',
          levels: [
            { bonus: 20, cost: 100 },
            { bonus: 40, cost: 200 },
            { bonus: 60, cost: 300 },
          ],
        },
        fortune: {
          id: 'fortune',
          name: '财运',
          description: '每次通关额外金币',
          levels: [
            { bonus: 5, cost: 100 },
            { bonus: 10, cost: 200 },
            { bonus: 15, cost: 300 },
          ],
        },
      },
    },
  },

  ENEMIES: {
    skeleton: {
      id: 'skeleton',
      name: '骷髅',
      hp: 30,
      speed: 60,
      damage: 1,
      expValue: 5,
      color: '#CCCCAA',
      size: 14,
      boss: { hp: 90, speed: 60, damage: 2, expValue: 25, size: 21 },
    },
    ghost: {
      id: 'ghost',
      name: '幽灵',
      hp: 20,
      speed: 80,
      damage: 1,
      expValue: 6,
      color: '#AACCFF',
      size: 12,
      boss: { hp: 60, speed: 80, damage: 2, expValue: 30, size: 18 },
    },
    gargoyle: {
      id: 'gargoyle',
      name: '石像鬼',
      hp: 60,
      speed: 40,
      damage: 2,
      expValue: 10,
      color: '#888899',
      size: 18,
      boss: { hp: 180, speed: 40, damage: 4, expValue: 50, size: 27 },
    },
    slime: {
      id: 'slime',
      name: '史莱姆',
      hp: 25,
      speed: 50,
      damage: 1,
      expValue: 4,
      color: '#44DD44',
      size: 12,
      boss: { hp: 75, speed: 50, damage: 2, expValue: 20, size: 18 },
    },
    bat: {
      id: 'bat',
      name: '蝙蝠',
      hp: 15,
      speed: 100,
      damage: 1,
      expValue: 4,
      color: '#664488',
      size: 10,
      boss: { hp: 45, speed: 100, damage: 2, expValue: 20, size: 15 },
    },
    zombie: {
      id: 'zombie',
      name: '僵尸',
      hp: 50,
      speed: 35,
      damage: 2,
      expValue: 8,
      color: '#668844',
      size: 16,
      boss: { hp: 150, speed: 35, damage: 4, expValue: 40, size: 24 },
    },
    demon: {
      id: 'demon',
      name: '恶鬼',
      hp: 80,
      speed: 55,
      damage: 3,
      expValue: 15,
      color: '#DD2222',
      size: 20,
      boss: { hp: 240, speed: 55, damage: 6, expValue: 75, size: 30 },
    },
    wraith: {
      id: 'wraith',
      name: '怨灵',
      hp: 45,
      speed: 75,
      damage: 2,
      expValue: 12,
      color: '#9944CC',
      size: 14,
      boss: { hp: 135, speed: 75, damage: 4, expValue: 60, size: 21 },
    },
  },

  WAVES: [
    { time: 0,   enemyTypes: ['skeleton', 'slime'],                         spawnRate: 0.8,  maxEnemies: 12 },
    { time: 30,  enemyTypes: ['skeleton', 'slime', 'bat'],                  spawnRate: 1.0,  maxEnemies: 15 },
    { time: 60,  enemyTypes: ['skeleton', 'ghost', 'bat'],                  spawnRate: 1.2,  maxEnemies: 18 },
    { time: 90,  enemyTypes: ['ghost', 'bat', 'slime'],                     spawnRate: 1.4,  maxEnemies: 20 },
    { time: 120, enemyTypes: ['gargoyle', 'zombie'],                        spawnRate: 1.0,  maxEnemies: 22, miniBoss: { type: 'gargoyle', count: 1 } },
    { time: 150, enemyTypes: ['ghost', 'zombie', 'bat'],                    spawnRate: 1.6,  maxEnemies: 24 },
    { time: 180, enemyTypes: ['zombie', 'gargoyle', 'wraith'],              spawnRate: 1.8,  maxEnemies: 26 },
    { time: 210, enemyTypes: ['wraith', 'ghost', 'gargoyle'],               spawnRate: 2.0,  maxEnemies: 28 },
    { time: 240, enemyTypes: ['demon', 'wraith', 'gargoyle'],               spawnRate: 1.5,  maxEnemies: 30, miniBoss: { type: 'demon', count: 1 } },
    { time: 270, enemyTypes: ['demon', 'wraith', 'zombie'],                 spawnRate: 2.2,  maxEnemies: 30 },
    { time: 300, enemyTypes: ['demon', 'wraith', 'gargoyle', 'zombie'],     spawnRate: 2.5,  maxEnemies: 32 },
    { time: 330, enemyTypes: ['demon', 'wraith', 'gargoyle'],               spawnRate: 2.8,  maxEnemies: 33 },
    { time: 360, enemyTypes: ['demon', 'wraith', 'ghost', 'gargoyle'],      spawnRate: 3.0,  maxEnemies: 34 },
    { time: 390, enemyTypes: ['demon', 'wraith', 'zombie', 'gargoyle'],     spawnRate: 3.2,  maxEnemies: 35 },
    { time: 420, enemyTypes: ['demon', 'wraith', 'gargoyle'],               spawnRate: 3.5,  maxEnemies: 35 },
    { time: 450, enemyTypes: ['demon', 'wraith'],                           spawnRate: 3.5,  maxEnemies: 35 },
    { time: 480, enemyTypes: ['demon'],                                     spawnRate: 0.5,  maxEnemies: 35, finalBoss: { type: 'demon', count: 1 } },
  ],

  MAPS: {
    dark_forest: {
      id: 'dark_forest',
      name: '暗黑森林',
      description: '幽暗的古老森林，弥漫着诅咒之气',
      icon: '🌲',
      worldWidth: 2000,
      worldHeight: 2000,
      unlockCondition: null,
      tileSize: 64,
      colors: { a: '#0d2818', b: '#132a1c', border: '#2ecc71' },
      fogColor: 'rgba(10,30,15,0.3)',
      decorations: [
        { type: 'tree', density: 0.06, colors: ['#1a4a2a', '#0d3318', '#245a34'] },
        { type: 'mushroom', density: 0.02, colors: ['#8e44ad', '#6c3483'] },
        { type: 'grass', density: 0.08, colors: ['#27ae60', '#1e8449'] }
      ],
      ambientParticles: { color: '#2ecc71', count: 15, type: 'firefly' }
    },
    lava_cave: {
      id: 'lava_cave',
      name: '熔岩洞窟',
      description: '地底深处的灼热洞窟，岩浆四溢',
      icon: '🌋',
      worldWidth: 1800,
      worldHeight: 1800,
      unlockCondition: { totalKills: 200 },
      tileSize: 64,
      colors: { a: '#2c1006', b: '#3a160a', border: '#e74c3c' },
      fogColor: 'rgba(40,10,0,0.25)',
      decorations: [
        { type: 'lava_crack', density: 0.04, colors: ['#e74c3c', '#c0392b'] },
        { type: 'rock', density: 0.05, colors: ['#4a3728', '#3d2e20', '#5c4633'] },
        { type: 'ember', density: 0.03, colors: ['#f39c12', '#e67e22'] }
      ],
      ambientParticles: { color: '#e74c3c', count: 20, type: 'ember' }
    },
    ice_realm: {
      id: 'ice_realm',
      name: '极寒冰原',
      description: '永霜覆盖的极地荒原，寒风刺骨',
      icon: '❄️',
      worldWidth: 2200,
      worldHeight: 2200,
      unlockCondition: { totalKills: 500 },
      tileSize: 64,
      colors: { a: '#0a1628', b: '#0e1e38', border: '#3498db' },
      fogColor: 'rgba(10,20,40,0.2)',
      decorations: [
        { type: 'ice_crystal', density: 0.04, colors: ['#a8d8ea', '#7ec8e3', '#57b0d4'] },
        { type: 'snow_pile', density: 0.06, colors: ['#dfe6e9', '#b2bec3'] },
        { type: 'frost', density: 0.05, colors: ['#74b9ff', '#a29bfe'] }
      ],
      ambientParticles: { color: '#dfe6e9', count: 25, type: 'snow' }
    },
    void_abyss: {
      id: 'void_abyss',
      name: '虚空深渊',
      description: '时空裂缝中的混沌之地，危机四伏',
      icon: '🌀',
      worldWidth: 2000,
      worldHeight: 2000,
      unlockCondition: { totalKills: 1000 },
      tileSize: 64,
      colors: { a: '#0a0015', b: '#10001f', border: '#9b59b6' },
      fogColor: 'rgba(15,0,30,0.3)',
      decorations: [
        { type: 'void_rift', density: 0.03, colors: ['#9b59b6', '#8e44ad', '#6c3483'] },
        { type: 'rune', density: 0.04, colors: ['#e056fd', '#be2edd'] },
        { type: 'crystal', density: 0.03, colors: ['#a29bfe', '#6c5ce7'] }
      ],
      ambientParticles: { color: '#9b59b6', count: 18, type: 'void' }
    }
  },
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = GameData;
}
